// RootLayout.jsx
import 'react-toastify/dist/ReactToastify.css';
import '@/styles/globals.scss';
import './globals.css';

// components
import GlobalProvider from '@/components/GlobalProvider';

export const metadata = {
  title: 'Payrun',
  description: 'Generated by create next app'
};

const RootLayout = ({ children }) => (
  <html lang="en">
    <body className="bg-light-white font-poppins">
      <GlobalProvider> {children}</GlobalProvider>
    </body>
  </html>
);

export default RootLayout;
